# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74d3fdd29391161fe74e9c15e75f49677331b011de3b39b4cf2640175c417d1ef448dab40b7d1b5314bfe4542ec9ea618464d93d041896036427f9cd50d8548f

test:
  secret_key_base: 771e425421e0ec705a770ba3f810280c1b6f78140f51b723666feaa9424a89827524abe1724fb5fdebddb476b0b47948c57983e430b7bcc8931a901549a2a462

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
